spring:
  profiles:
    active: dev  # 指定配置文件
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

  # 项目自定义配置
  myconfig:
    # md5的盐
    md5-salt: myfunds
    # 是否明文存储密码
    is-pw: true
    # 是否彩色SQl日志
    color-sql: true